### ISSUE TITLE
when run spike_test bug

### ISSUE THREAD

**Issue by wangzhenyu32** [THU-DSP-LAB/ventus-gpgpu-isa-simulator#4]
Env:
LIBRARY_PATH=/root/ventus/llvm-project/install/lib
LD_LIBRARY_PATH=/root/ventus/llvm-project/install/lib
SPIKE_TARGET_DIR=/root/ventus/llvm-project/install/lib

Error:
./spike_test: symbol lookup error: ./spike_test: undefined symbol: _Z16vt_copy_from_devPvmS_mmm

**Comment by yangkex** [comment]
Seems you use build-ventus.sh in ventus-llvm to build this project.
try to set `SPIKE_TARGET_DIR=/root/ventus/llvm-project/install`
