### ISSUE TITLE
[optimization] optimize the spike log format to adapt the need of script compare

### ISSUE THREAD

**Issue by yangzexia** [THU-DSP-LAB/ventus-gpgpu-isa-simulator#6]
```
core  2: 0x80000214 (0x0003a3fb) vlw12.v v7, v7, 0
core  2: 3 0x80000214 (0x0003a3fb) e32 m1 l4 v7  0x00000000800000003f2aaaaa3f000000 c8_vstart 0x00000000 mem 0x90002010 mem 0x90002020 mem 0x90002030
```

同时这里对应的Chisel log如下，mask索引、向量元素索引和地址都是降序。

```
warp 1 0x80000214 0x0003a3fb lsu.r v  7 op 3 @ 00000000+00000000 90002030+00000000 90002020+00000000 90002010+00000000
...
warp 1 0x80000214 0x0003a3fb v  7 0111 00000000 80000000 3f2aaaaa 3f000000
```

同时相比之下，spike侧缺少了mask信息（包括计算指令也都缺mask），mem也只有3条，并不能分清哪个元素对应哪个地址。

## 3.

分支汇合类指令的mask npc rpc感觉塞进一行好一些。

barrier会打出一堆单行没有指令字符串的log，这个是正常现象吗？

**Comment by ghost** [comment]
```
0x800000dc (0x0000a0fb) vlw12.v v1, v1, 0
core   0: 3 0x800000dc (0x0000a0fb) e32 m1 l32 v1  0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040a000004080000040400000400000003f80000000000000 c8_vstart 0x00000000 mem 0x90000000 mem 0x90000004 mem 0x90000008 mem 0x9000000c mem 0x90000010 mem 0x90000014 mem 0x90000018 mem 0x9000001c mem 0x90000020 mem 0x90000024 mem 0x90000028 mem 0x9000002c mem 0x90000030 mem 0x90000034 mem 0x90000038 mem 0x9000003c mem 0x90000040 mem 0x90000044 mem 0x90000048 mem 0x9000004c mem 0x90000050 mem 0x90000054 mem 0x90000058 mem 0x9000005c mem 0x90000060 mem 0x90000064 mem 0x90000068 mem 0x9000006c mem 0x90000070 mem 0x90000074 mem 0x90000078 mem 0x9000007c
```
关于这种访存指令的log，可不可以打印成mem 0x9000007c val 0x00000000这种形式，或者0x000000000000000...这些数据之间用空格分割开来，因为有时候确实得自己去数8个数字，其它指令执行完的数据格式也类似

**Comment by ghost** [comment]
结合log信息
```
### Triple: riscv32, CPU: ventus-gpgpu
Warning: the memory at  [0x90000000, 0x90000017] has been realigned
to the 4 KiB page size: [0x90000000, 0x90000FFF]
to allocate at 0x90000000 with 4096 bytes 
to copy to 0x90000000 with 24 bytes
Warning: the memory at  [0x90001000, 0x90001017] has been realigned
to the 4 KiB page size: [0x90001000, 0x90001FFF]
to allocate at 0x90001000 with 4096 bytes 
to copy to 0x90001000 with 24 bytes
Warning: the memory at  [0x90002000, 0x90002017] has been realigned
to the 4 KiB page size: [0x90002000, 0x90002FFF]
to allocate at 0x90002000 with 4096 bytes 
to copy to 0x90000000 with 24 bytes
to copy to 0x90001000 with 24 bytes
to copy to 0x90000000 with 24 bytes
to copy to 0x90001000 with 24 bytes
notice that ventus hasn't support local buffer as argument yet.
Warning: the memory at  [0x90003000, 0x9000300B] has been realigned
to the 4 KiB page size: [0x90003000, 0x90003FFF]
to allocate at 0x90003000 with 4096 bytes 
to copy to 0x90003000 with 12 bytes
to allocate at 0x90004000 with 131072 bytes 
Warning: the memory at  [0x90024000, 0x9002403F] has been realigned
to the 4 KiB page size: [0x90024000, 0x90024FFF]
to allocate at 0x90024000 with 4096 bytes 
to copy to 0x90024000 with 64 bytes
```
其实以上有很多打印信息是无用信息，是否可以设置一个开关，类似`POCL_DEBUG=all`这种，控制打印行为，就比如我跑测试时，其实只关注测试成功与否，并不想看这些信息，看信息我会去log文件看是吧，测试出错的时候，我才会想看到具体的程序报错，其他的控制台信息我们是不会关心的

**Comment by yangzexia** [comment]
> ```
> 0x800000dc (0x0000a0fb) vlw12.v v1, v1, 0
> core   0: 3 0x800000dc (0x0000a0fb) e32 m1 l32 v1  0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040a000004080000040400000400000003f80000000000000 c8_vstart 0x00000000 mem 0x90000000 mem 0x90000004 mem 0x90000008 mem 0x9000000c mem 0x90000010 mem 0x90000014 mem 0x90000018 mem 0x9000001c mem 0x90000020 mem 0x90000024 mem 0x90000028 mem 0x9000002c mem 0x90000030 mem 0x90000034 mem 0x90000038 mem 0x9000003c mem 0x90000040 mem 0x90000044 mem 0x90000048 mem 0x9000004c mem 0x90000050 mem 0x90000054 mem 0x90000058 mem 0x9000005c mem 0x90000060 mem 0x90000064 mem 0x90000068 mem 0x9000006c mem 0x90000070 mem 0x90000074 mem 0x90000078 mem 0x9000007c
> ```
> 
> 关于这种访存指令的log，可不可以打印成mem 0x9000007c val 0x00000000这种形式，或者0x000000000000000...这些数据之间用空格分割开来，因为有时候确实得自己去数8个数字，其它指令执行完的数据格式也类似

可以实现在每个32位数之间加一个空格

**Comment by yangzexia** [comment]
> 结合log信息
> 
> ```
> ### Triple: riscv32, CPU: ventus-gpgpu
> Warning: the memory at  [0x90000000, 0x90000017] has been realigned
> to the 4 KiB page size: [0x90000000, 0x90000FFF]
> to allocate at 0x90000000 with 4096 bytes 
> to copy to 0x90000000 with 24 bytes
> Warning: the memory at  [0x90001000, 0x90001017] has been realigned
> to the 4 KiB page size: [0x90001000, 0x90001FFF]
> to allocate at 0x90001000 with 4096 bytes 
> to copy to 0x90001000 with 24 bytes
> Warning: the memory at  [0x90002000, 0x90002017] has been realigned
> to the 4 KiB page size: [0x90002000, 0x90002FFF]
> to allocate at 0x90002000 with 4096 bytes 
> to copy to 0x90000000 with 24 bytes
> to copy to 0x90001000 with 24 bytes
> to copy to 0x90000000 with 24 bytes
> to copy to 0x90001000 with 24 bytes
> notice that ventus hasn't support local buffer as argument yet.
> Warning: the memory at  [0x90003000, 0x9000300B] has been realigned
> to the 4 KiB page size: [0x90003000, 0x90003FFF]
> to allocate at 0x90003000 with 4096 bytes 
> to copy to 0x90003000 with 12 bytes
> to allocate at 0x90004000 with 131072 bytes 
> Warning: the memory at  [0x90024000, 0x9002403F] has been realigned
> to the 4 KiB page size: [0x90024000, 0x90024FFF]
> to allocate at 0x90024000 with 4096 bytes 
> to copy to 0x90024000 with 64 bytes
> ```
> 
> 其实以上有很多打印信息是无用信息，是否可以设置一个开关，类似`POCL_DEBUG=all`这种，控制打印行为，就比如我跑测试时，其实只关注测试成功与否，并不想看这些信息，看信息我会去log文件看是吧，测试出错的时候，我才会想看到具体的程序报错，其他的控制台信息我们是不会关心的

这个问题属于pocl，建议在pocl那边开一个issue讨论

**Comment by yangzexia** [comment]
> ```
> 0x800000dc (0x0000a0fb) vlw12.v v1, v1, 0
> core   0: 3 0x800000dc (0x0000a0fb) e32 m1 l32 v1  0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040a000004080000040400000400000003f80000000000000 c8_vstart 0x00000000 mem 0x90000000 mem 0x90000004 mem 0x90000008 mem 0x9000000c mem 0x90000010 mem 0x90000014 mem 0x90000018 mem 0x9000001c mem 0x90000020 mem 0x90000024 mem 0x90000028 mem 0x9000002c mem 0x90000030 mem 0x90000034 mem 0x90000038 mem 0x9000003c mem 0x90000040 mem 0x90000044 mem 0x90000048 mem 0x9000004c mem 0x90000050 mem 0x90000054 mem 0x90000058 mem 0x9000005c mem 0x90000060 mem 0x90000064 mem 0x90000068 mem 0x9000006c mem 0x90000070 mem 0x90000074 mem 0x90000078 mem 0x9000007c
> ```
> 
> 关于这种访存指令的log，可不可以打印成mem 0x9000007c val 0x00000000这种形式，或者0x000000000000000...这些数据之间用空格分割开来，因为有时候确实得自己去数8个数字，其它指令执行完的数据格式也类似

log修改之后，load和store的格式将不相同（该修改还未提交，如果认可该修改，将在后续提交到modify_log_format分支）
```
 core   0: 0x800000e8 (0x0001217b) vlw12.v v2, v2, 0
core   0: 3 0x800000e8 (0x0001217b) e32 m1 l8 v2  0x00000000 00000000 3f800000 40000000 40400000 40800000 40a00000 40c00000  c8_vstart 0x00000000     mem 0x90001000 mem 0x90001004 mem 0x90001008 mem 0x9000100c mem 0x90001010 mem 0x90001014 mem 0x90001018 mem 0x9000101c
core   0: 0x800000ec (0x021110d7) vfadd.vv v1, v1, v2
core   0: 3 0x800000ec (0x021110d7) c8_vstart 0x00000000 e32 m1 l8 v1  0x00000000 00000000 40c00000 40c00000 40c00000 40c00000 40c00000 40c00000
core   0: 0x800000f0 (0xff412283) lw      x5, -12(x2)
core   0: 3 0x800000f0 (0xff412283) x5  0x90002000 mem 0x70000004
core   0: 0x800000f4 (0x0202c057) vadd.vx v0, v0, x5
core   0: 3 0x800000f4 (0x0202c057) c8_vstart 0x00000000 e32 m1 l8 v0  0x9000201c 90002018 90002014 90002010 9000200c 90002008 90002004 90002000
core   0: 0x800000f8 (0x0010607b) vsw12.v v1, v0, 0
core   0: 3 0x800000f8 (0x0010607b) c8_vstart 0x00000000 e32 m1 l8 mem 0x90002000 0x40c00000 mem 0x90002004 0x40c00000 mem 0x90002008 0x40c00000 mem 0x9000200c 0x40c00000 mem 0x90002010 0x40c00000 mem 0x90002014 0x40c00000 mem 0x90002018 0x00000000 mem 0x9000201c 0x00000000
```

**Comment by ghost** [comment]
LGTM
